services:
  mysql:
    image: mysql:8
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mypetyourpet
    ports:
      - "3307:3306"
    volumes:
      - mypetyourpet_db:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mypetyourpet_db:


