services:
  backend:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - APP_UPLOAD_DIR=/app/uploads
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mypetyourpet
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mypetyourpet
    ports:
      - "3307:3306"
    volumes:
      - mypetyourpet_db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mypetyourpet_db:


